DAPP-460: Error UI: Chain Info
Topl/flutter_annulus pull request #129
Opened 2023-12-13 20:34 UTC by lukorito

## Description

Add chain failed UI
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
![Screenshot 2023-12-13 at 23 26 58](https://github.com/Topl/flutter_annulus/assets/42966323/b567d8f2-5785-48f6-8c9d-bac9114d461a)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have added screenshots

2023-12-13 23:06 UTC, KalervoHyyppa requested changes
Wait until DAPP-447 is merged then pull that into this branch

2023-12-15 13:34 UTC, lukorito commented
> Wait until DAPP-447 is merged then pull that into this branch

@KalervoHyyppa this is ready for review

2023-12-18 15:03 UTC, berriose approved these changes

2023-12-18 16:34 UTC, KalervoHyyppa approved these changes

2023-12-18 16:51 UTC, merged