DAPP-455 Faucet Link
Topl/flutter_annulus pull request #132
Opened 2023-12-15 22:19 UTC by berriose

## Description

- Adds a faucet link in the desktop view
- required test obj
- desktop tests

Please note:

1. no mobile designs were provided. This is only on desktop
2. I adjusted the placement of the light/dark theme toggle to confirm to the Figma designs. It is now to the right of the chainname dropdown menu
3. I believe the spacing on the designs 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] manual
- [ ] automated testing

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have added screenshots

2023-12-15 22:24 UTC, berriose commented
<img width="1440" alt="Screenshot 2023-12-15 at 4 23 52 PM" src="https://github.com/Topl/flutter_annulus/assets/43301025/ff102b63-46aa-4dac-b989-cfd23c2238c5">

2023-12-18 16:20 UTC, KalervoHyyppa requested changes
See 1 small comment

2023-12-18 16:20 UTC, KalervoHyyppa commented on lib/shared/widgets/header.dart
> +  static const Key hyperlinkKey = Key('menuKey');
Rename this to `Key('hyperlinkKey');`

2023-12-18 17:17 UTC, KalervoHyyppa approved these changes

2023-12-18 17:21 UTC, merged