Product: Summary of key stats
Topl/flutter_annulus pull request #17
Opened 2023-05-05 13:09 UTC by lukorito

Add mock state to chain

2023-05-05 13:29 UTC, Kelz29 approved these changes

2023-05-05 13:34 UTC, berriose commented on lib/chain/sections/chain_info.dart
> +    print(chainInfo);
cleanup

2023-05-05 13:45 UTC, KalervoHyyppa requested changes
Most of our providers will be using `AsyncValue`, so it's best to implement `.when` when nescassary

2023-05-05 13:45 UTC, KalervoHyyppa commented on lib/chain/sections/chain_info.dart
> +    final chainInfo = ref.watch(chainProvider).value;
Remove `.value` and just do `final chainInfo = ref.watch(chainProvider)` and then implement a `.when` in the UI below

2023-05-05 13:45 UTC, KalervoHyyppa commented on lib/chain/sections/chain_info.dart
>        child: Column(
Wrap this in a `chainInfo.when`. You may have to do some research, here's the documentation: https://pub.dev/documentation/riverpod/latest/riverpod/AsyncValue-class.html

2023-05-08 11:40 UTC, lukorito commented on lib/chain/sections/chain_info.dart
>        child: Column(
@KalervoHyyppa I have implemented the feedback as requested.

2023-05-08 15:39 UTC, KalervoHyyppa approved these changes
LGTM

2023-05-08 16:30 UTC, merged