add chart
Topl/flutter_annulus pull request #32
Opened 2023-05-19 13:09 UTC by lukorito

2023-05-22 10:40 UTC, ultimaterex commented on lib/chain/sections/line_graph.dart
> +      break;
Should these be hardcoded in?

2023-05-22 10:42 UTC, ultimaterex requested changes
Hardcoded date values should be from some kind of method arg. 

And the theming data incl colors should be extracted to a separate file.

2023-05-22 20:24 UTC, lukorito commented
> 

Noted on this. However, the idea was to get the UI going. Once we have the mock state ready, we can refactor accordingly. I will implement the feedback on the colors though. Thank you @ultimaterex

2023-05-23 12:20 UTC, Kelz29 approved these changes

2023-05-23 12:20 UTC, merged