update transaction fields
Topl/flutter_annulus pull request #55
Opened 2023-06-15 04:55 UTC by berriose

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have added screenshots

2023-07-11 18:49 UTC, KalervoHyyppa requested changes
Putting this here to give me some time to review

2023-07-12 19:40 UTC, KalervoHyyppa commented on lib/blocks/providers/block_provider.dart
> +    size: 5432.2,
Where does the block size come from?

2023-07-12 19:42 UTC, KalervoHyyppa commented on lib/blocks/providers/block_provider.dart
> +    size: 5432.2,
Same for size here

2023-07-12 20:32 UTC, berriose commented on lib/blocks/providers/block_provider.dart
> +    size: 5432.2,
It's a placeholder. I didn't see a way to get the size in the methods.

2023-07-13 19:57 UTC, KalervoHyyppa requested changes
Block provider looks good

2023-07-13 20:35 UTC, berriose commented on lib/transactions/providers/transactions_provider.dart
> +  if (blockRes.block.fullBody.hasField(1)) {
I'll add a comment there. The fullbody is empty if there are no transactions. This checks for transactions.

2023-07-14 16:45 UTC, KalervoHyyppa approved these changes
Looks good!

2023-07-14 17:13 UTC, merged