update model values
Topl/flutter_annulus pull request #86
Opened 2023-07-21 13:10 UTC by berriose

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have added screenshots

2023-07-25 13:36 UTC, berriose commented on lib/transactions/models/transaction.dart
>      required double transactionFee,
It looks like since the data is encoded as Big Ints on chain, a double is not needed. Should I go ahead and change this data type to Big Int?

2023-07-25 13:39 UTC, berriose commented on lib/transactions/sections/transaction_details_drawer.dart
> +                ...createAddressWidgets(addresses: transaction!.senderAddress),
I made this method in order to display multiple addresses, but I didn't see them when I clicked on a transaction. I also saw a lot of mock data, so I wasn't sure where we need to remove the mock data and add in this real data. I have this here to avoid errors and still have commented code below. I'm going to clean it up, but if anyone has any suggestions for this, I'm all ears.

2023-07-25 21:01 UTC, KalervoHyyppa requested changes
See comments

2023-07-25 21:01 UTC, KalervoHyyppa commented on lib/transactions/sections/transaction_details_drawer.dart
> +                ...createAddressWidgets(addresses: transaction!.senderAddress),
I'd make this into it's own component (can be within this file) instead of doing this in the utils file

2023-07-25 21:39 UTC, berriose commented on lib/transactions/providers/transactions_provider.dart
>        transactionSize: 10,
I missed this. I'll update this.

2023-07-26 13:59 UTC, KalervoHyyppa approved these changes
LGTM

2023-07-26 15:24 UTC, merged