Cached Networks
Topl/flutter_annulus pull request #90
Opened 2023-08-03 13:25 UTC by berriose

## Description

- pull networks from cache
- add a new network to cache

Fixes # (issue)

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Manual

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have added screenshots

2023-08-04 13:57 UTC, KalervoHyyppa commented on lib/chain/models/currency.dart
> +Currency convertStringToCurrency({required String currencyString}) {
You can delete the list of strings and just used an enhance `enum` and add `string` as a property. See chart_option.dart for an example

2023-08-04 13:58 UTC, KalervoHyyppa commented on lib/chain/providers/selected_chain_provider.dart
> +      Future.delayed(const Duration(seconds: 1), () {
Remove `Future.delayed` it was here just to show loading UI

2023-08-04 14:01 UTC, KalervoHyyppa requested changes
See comments

2023-08-04 15:11 UTC, berriose commented on pubspec.yaml
> +  hive_flutter: ^1.1.0
Yes, we need hive for the hive cache and hive_flutter to use it with flutter apps.

2023-08-04 18:24 UTC, KalervoHyyppa requested changes
A couple of more changes

2023-08-04 18:24 UTC, KalervoHyyppa commented on lib/chain/models/chains.dart
> +  if (int == null) {
I think you meant to use `port` here

2023-08-04 18:24 UTC, KalervoHyyppa commented on lib/chain/sections/chainname_dropdown.dart
When adding a new chain, it doesn't automatically appear in the dropdown

2023-08-04 20:08 UTC, berriose commented on lib/chain/models/chains.dart
> +  if (int == null) {
thanks for catching this.

2023-08-16 19:58 UTC, KalervoHyyppa approved these changes
Nice, it's good to go

2023-08-16 20:53 UTC, merged