ANNULUS-289 Refactor Getting Next Block
Topl/flutter_annulus pull request #92
Opened 2023-08-07 04:24 UTC by berriose

## Description

- refactor getting the next block that contains transactions
- when fetching the next transaction for adding to state, search for the next block that has transaction instead of assuming that the next block down the chain has transactions.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have added screenshots

2023-08-07 11:48 UTC, lukorito approved these changes

2023-08-07 16:58 UTC, KalervoHyyppa requested changes
Make sure to add blocks to state as they are requested

2023-08-07 16:58 UTC, KalervoHyyppa commented on lib/transactions/utils/utils.dart
> +Future<BlockResponse> getFirstPopulatedBlock({required GenusGRPCService genusClient}) async {
This should work, but this should be in the blockProivder and should add blocks to the state as well. It will decrease read amounts.

2023-08-07 16:58 UTC, KalervoHyyppa commented on lib/transactions/utils/utils.dart
> +Future<BlockResponse> getNextPopulatedBlock({required GenusGRPCService genusClient, required int height}) async {
This should work, but this should be in the blockProivder and should add blocks to the state as well. It will decrease read amounts.

2023-08-15 19:12 UTC, KalervoHyyppa approved these changes
LGTM

2023-08-16 13:22 UTC, merged